apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitea-postgresql-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/data/postgress"