apiVersion: v1
kind: Service
metadata:
  name: gitea-node
  labels:
    name: gitea
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      name: http  
  selector:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/name: gitea