# https://github.com/dennyzhang/cheatsheet-kubernetes-A4
# https://cheatsheet.dennyzhang.com/kubernetes-yaml-templates
apiVersion: v1
kind: Pod
metadata:
  name: alpine
  namespace: default
  labels:
    env: test
spec:
  containers:
  - name: alpine
    image: alpine:latest
    command:
      - /bin/sh
      - "-c"
      - "sleep 60m"
  dnsConfig:
    nameservers:
      - 8.8.8.8