apiVersion: v1
kind: Pod
metadata:
  name: proxy
  labels:
    app: frontend
    env: test
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP