# https://kubernetes.io/docs/concepts/services-networking/ingress/
# https://medium.com/google-cloud/kubernetes-nodeport-vs-loadbalancer-vs-ingress-when-should-i-use-what-922f010849e0
apiVersion: v1
kind: Service
metadata:  
  name: service_deployment_nginx
  namespace: default
spec:
  selector:    
    label: nginx_template_pod
  type: NodePort
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
    protocol: TCP
